#!/bin/bash

NAME=open_books
DIR=/home/scraper_admin/
co-author-for-open_books
USER=scraper_admin
GROUP=scraper_admin
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn app:app \
--name $NAME \
--workers $WORKERS \
--worker-class $WORKER_CLASS \
--user=$USER \
--group=$GROUP \
--bind=$BIND \
--forwarded-allow-ips="*"\
--log-level=$LOG_LEVEL \
--log-file=-